/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#3F7449",
        "primary-pressed": "#356239",
        "primary-foreground": "#F3FAF4",
        "accent-muted": "#A1C8A8",
        "accent-muted-foreground": "#1B3320",
        recording: "#E5484D",
        success: "#3F7449",
        warning: "#D9A441",
        destructive: "#E5484D",
        background: "#0A0D0B",
        surface: "#141917",
        "surface-raised": "#1B211E",
        border: "#242B26",
        "border-strong": "#333C36",
        "text-primary": "#F2F5F3",
        "text-secondary": "#9BA79E",
        "text-muted": "#6B766F",
        disabled: "#3A423D",
      },
      borderRadius: {
        sm: "6px",
        md: "8px",
        lg: "10px",
        xl: "14px",
      },
      fontFamily: {
        sans: ["PlusJakartaSans_400Regular"],
        "sans-medium": ["PlusJakartaSans_500Medium"],
        "sans-semibold": ["PlusJakartaSans_600SemiBold"],
        "sans-bold": ["PlusJakartaSans_700Bold"],
        display: ["SpaceGrotesk_700Bold"],
        "display-medium": ["SpaceGrotesk_500Medium"],
        "display-semibold": ["SpaceGrotesk_600SemiBold"],
      },
    },
  },
  plugins: [],
}